# main.py
from flask import Flask, request, jsonify
from flask_cors import CORS
from anthropic import Anthropic
import os
import json
from datetime import datetime
import resend

app = Flask(__name__)
CORS(app)

# API clients
client = Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
resend.api_key = os.environ.get("RESEND_API_KEY")

# Counter file (in production, use a database)
COUNTER_FILE = 'rejection_counter.json'

def get_counter():
    try:
        with open(COUNTER_FILE, 'r') as f:
            data = json.load(f)
            return data.get('count', 0)
    except FileNotFoundError:
        return 0

def increment_counter():
    count = get_counter() + 1
    with open(COUNTER_FILE, 'w') as f:
        json.dump({'count': count, 'last_updated': datetime.now().isoformat()}, f)
    return count

def send_rejection_email(to_email, rejection_text, company, role):
    """Send the rejection letter via email"""
    try:
        params = {
            "from": "The Transition Project <rejections@nevoalmog.com>",
            "to": [to_email],
            "subject": f"Your Application Update from {company}",
            "html": f"""
            <div style="font-family: 'Space Grotesk', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px; background-color: #F2F2F0;">
                <div style="background: #F2F2F0; border-left: 3px solid #4B5F44; padding: 30px; margin-bottom: 30px;">
                    <p style="white-space: pre-wrap; line-height: 1.8; color: #1A1C1A; font-size: 15px;">{rejection_text}</p>
                </div>
                <div style="border-top: 1px solid rgba(133, 128, 120, 0.3); padding-top: 20px; text-align: center;">
                    <p style="color: #858078; font-size: 13px; margin-bottom: 10px;">
                        This rejection letter was generated by The Transition Project
                    </p>
                    <p style="color: #858078; font-size: 13px;">
                        Role: {role} at {company}
                    </p>
                    <a href="https://www.nevoalmog.com" style="color: #4B5F44; text-decoration: none; font-size: 13px;">
                        Learn more about The Transition Project →
                    </a>
                </div>
            </div>
            """,
            "text": f"{rejection_text}\n\n---\nGenerated by The Transition Project\nRole: {role} at {company}"
        }
        
        email = resend.Emails.send(params)
        return True, email
    except Exception as e:
        print(f"Email error: {e}")
        return False, str(e)

@app.route('/api/counter', methods=['GET'])
def counter():
    """Get current rejection count"""
    return jsonify({'count': get_counter()})

@app.route('/api/generate', methods=['POST'])
def generate_rejection():
    """Generate rejection letter"""
    try:
        data = request.json
        first_name = data.get('firstName', 'Candidate')
        last_name = data.get('lastName', '')
        company = data.get('company', 'TechCorp')
        role = data.get('role', 'Product Manager')
        email = data.get('email', None)
        
        # Increment counter
        new_count = increment_counter()
        
        # Generate rejection letter with updated prompt
        prompt = f"""Generate a rejection letter from {company} for the role of {role}.
The candidate's name is {first_name} {last_name}.

STRUCTURE - THIS IS CRUCIAL:

PARAGRAPH 1 - CORPORATE OPENING:
Start with a completely standard, dry corporate rejection opening. "Dear {first_name}, thank you for taking the time... after careful consideration... we regret to inform you..." 
Make it feel like every other rejection letter ever written. Professional. Distant. Template-like.

PARAGRAPH 2 - THE BREAK (THIS IS THE HEART):
Suddenly, the tone shifts. The letter becomes unexpectedly human. Not sarcastic, not satirical—genuinely warm and honest. 
The recruiter breaks character and speaks directly to the reader about what really matters:
- Getting a "no" is okay. It's part of the journey.
- We're all living through strange, uncertain times.
- A rejection letter doesn't define your worth.
- The courage to apply, to try, to keep going—that's what matters.
- This letter will be forgotten. So will this rejection. What won't be forgotten: your health, your peace of mind, the people who love you.
- Something like: "Between you and me, none of this really matters as much as we pretend it does."

PARAGRAPH 3 - BACK TO CORPORATE:
Snap back to dry corporate tone abruptly. "We wish you the best in your future endeavors. Best regards, [Name], Talent Acquisition Team."
The contrast should feel almost jarring—like the human moment never happened.

IMPORTANT:
- The middle paragraph should feel like genuine care breaking through, not irony or satire
- It should make the reader feel seen, not mocked
- The return to corporate speak at the end should feel almost absurd after what came before
- Total length: 180-220 words

Sign off with a realistic recruiter name and title."""

        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=1024,
            messages=[{
                "role": "user",
                "content": prompt
            }]
        )
        
        rejection_text = message.content[0].text
        
        # Send email if provided
        email_sent = False
        if email:
            email_sent, _ = send_rejection_email(email, rejection_text, company, role)
        
        return jsonify({
            'success': True,
            'rejection_letter': rejection_text,
            'count': new_count,
            'company': company,
            'role': role,
            'email_sent': email_sent
        })
        
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@app.route('/health', methods=['GET'])
def health():
    return jsonify({'status': 'healthy'})

if __name__ == '__main__':
    app.run(debug=True, port=5000)
