# main.py - HAIKU ENGINE + SMART PROMPT (The Winner)
from flask import Flask, request, jsonify
from flask_cors import CORS
from anthropic import Anthropic
import os
import json
from datetime import datetime
import resend

app = Flask(__name__)
CORS(app)

# API clients
client = Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
resend.api_key = os.environ.get("RESEND_API_KEY")

# Counter file logic
COUNTER_FILE = 'rejection_counter.json'

def get_counter():
    try:
        if not os.path.exists(COUNTER_FILE):
            return 0
        with open(COUNTER_FILE, 'r') as f:
            data = json.load(f)
            return data.get('count', 0)
    except Exception as e:
        print(f"Counter Read Error: {e}")
        return 0

def increment_counter():
    try:
        current_count = get_counter()
        new_count = current_count + 1
        with open(COUNTER_FILE, 'w') as f:
            json.dump({'count': new_count, 'last_updated': datetime.now().isoformat()}, f)
        return new_count
    except Exception as e:
        print(f"Counter Write Error: {e}")
        return get_counter() + 1

def send_rejection_email(to_email, rejection_text, company, role):
    """Send the rejection letter via email"""
    try:
        params = {
            "from": "The Transition Project <rejections@nevoalmog.com>",
            "to": [to_email],
            "subject": f"Update regarding your application to {company}",
            "html": f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
                <p style="white-space: pre-wrap; line-height: 1.6; color: #333;">{rejection_text}</p>
                <br>
                <hr>
                <p style="color: #888; font-size: 12px;">
                    Generated by The Transition Project<br>
                    Role: {role} at {company}
                </p>
            </div>
            """,
            "text": f"{rejection_text}\n\n---\nGenerated by The Transition Project"
        }
        
        email = resend.Emails.send(params)
        return True, email
    except Exception as e:
        print(f"Email error: {e}")
        return False, str(e)

@app.route('/api/counter', methods=['GET'])
def counter():
    return jsonify({'count': get_counter()})

@app.route('/api/generate', methods=['POST'])
def generate_rejection():
    try:
        data = request.json
        first_name = data.get('firstName', 'Candidate')
        last_name = data.get('lastName', '')
        company = data.get('company', 'TechCorp')
        role = data.get('role', 'Product Manager')
        email = data.get('email', None)
        
        new_count = increment_counter()
        
        # THE SMART PROMPT (Sandwich Method)
        prompt = f"""Generate a rejection letter from {company} for the role of {role}.
The candidate's name is {first_name} {last_name}.

STRUCTURE - THIS IS CRUCIAL:

PARAGRAPH 1 - CORPORATE OPENING:
Start with a completely standard, dry corporate rejection opening. "Dear {first_name}, thank you for taking the time... after careful consideration... we regret to inform you..." 
Make it feel like every other rejection letter ever written. Professional. Distant. Template-like.

PARAGRAPH 2 - THE BREAK (THIS IS THE HEART):
Suddenly, the tone shifts. The letter becomes unexpectedly human. Not sarcastic, not satirical—genuinely warm and honest. 
The recruiter breaks character and speaks directly to the reader about what really matters:
- Getting a "no" is okay. It's part of the journey.
- A rejection letter doesn't define your worth.
- The courage to apply, to try, to keep going—that's what matters.
- Mention something like: "Between you and me, none of this really matters as much as we pretend it does."
- Tell them to keep believing in what they are building toward.

PARAGRAPH 3 - BACK TO CORPORATE:
Snap back to dry corporate tone abruptly. "We wish you the best in your future endeavors."
The contrast should feel almost jarring—like the human moment never happened.

CRITICAL FORMATTING RULES:
1. Do NOT include a subject line.
2. Do NOT write the company name at the top.
3. Start directly with "Dear {first_name},"
4. Sign off with a REALISTIC, INVENTED human name (e.g., 'Sarah Jenkins', 'David Cohen', 'Emma Thompson') and a title like 'Talent Acquisition Lead'. Do not use placeholders."""

        # Back to Haiku (The only one that works for your account)
        message = client.messages.create(
            model="claude-3-haiku-20240307",
            max_tokens=1024,
            messages=[{
                "role": "user",
                "content": prompt
            }]
        )
        
        rejection_text = message.content[0].text
        
        email_sent = False
        if email:
            email_sent, _ = send_rejection_email(email, rejection_text, company, role)
        
        return jsonify({
            'success': True,
            'rejection_letter': rejection_text,
            'count': new_count,
            'company': company,
            'role': role,
            'email_sent': email_sent
        })
        
    except Exception as e:
        print(f"CRITICAL ERROR: {str(e)}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@app.route('/health', methods=['GET'])
def health():
    return jsonify({'status': 'healthy'})

if __name__ == '__main__':
    app.run(debug=True, port=5000)
