# main.py - FINAL VERSION (Name Fix + Live Counter)
from flask import Flask, request, jsonify
from flask_cors import CORS
from anthropic import Anthropic
import os
import json
from datetime import datetime
import resend

app = Flask(__name__)
CORS(app)

# API clients
client = Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
resend.api_key = os.environ.get("RESEND_API_KEY")

# Counter file logic
COUNTER_FILE = 'rejection_counter.json'

def get_counter():
    try:
        if not os.path.exists(COUNTER_FILE):
            return 0
        with open(COUNTER_FILE, 'r') as f:
            data = json.load(f)
            return data.get('count', 0)
    except Exception as e:
        print(f"Counter Read Error: {e}")
        return 0

def increment_counter():
    try:
        current_count = get_counter()
        new_count = current_count + 1
        with open(COUNTER_FILE, 'w') as f:
            json.dump({'count': new_count, 'last_updated': datetime.now().isoformat()}, f)
        return new_count
    except Exception as e:
        print(f"Counter Write Error: {e}")
        return get_counter() + 1 # Fallback to just incrementing in memory for this request

def send_rejection_email(to_email, rejection_text, company, role):
    """Send the rejection letter via email"""
    try:
        params = {
            "from": "The Transition Project <rejections@nevoalmog.com>",
            "to": [to_email],
            "subject": f"Update regarding your application to {company}",
            "html": f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
                <p style="white-space: pre-wrap; line-height: 1.6; color: #333;">{rejection_text}</p>
                <br>
                <hr>
                <p style="color: #888; font-size: 12px;">
                    Generated by The Transition Project<br>
                    Role: {role} at {company}
                </p>
            </div>
            """,
            "text": f"{rejection_text}\n\n---\nGenerated by The Transition Project"
        }
        
        email = resend.Emails.send(params)
        return True, email
    except Exception as e:
        print(f"Email error: {e}")
        return False, str(e)

@app.route('/api/counter', methods=['GET'])
def counter():
    return jsonify({'count': get_counter()})

@app.route('/api/generate', methods=['POST'])
def generate_rejection():
    try:
        data = request.json
        first_name = data.get('firstName', 'Candidate')
        last_name = data.get('lastName', '')
        company = data.get('company', 'TechCorp')
        role = data.get('role', 'Product Manager')
        email = data.get('email', None)
        
        # This is where the magic happens - actually updating the file
        new_count = increment_counter()
        
        prompt = f"""Write a rejection letter from {company} for the role of {role} to {first_name} {last_name}.

CRITICAL RULES:
1. Do NOT write a subject line.
2. Do NOT write the company name at the top.
3. Start strictly with "Dear {first_name},"

Structure:
- Paragraph 1: Standard corporate rejection ("Thank you for applying...").
- Paragraph 2: The "Break". Suddenly warm, honest, human. Tell them this rejection doesn't define them. "Between you and me..."
- Paragraph 3: Back to corporate closing ("Best regards...").

Sign off with a REALISTIC, INVENTED human name (e.g., 'Sarah Jenkins', 'David Cohen', 'Emma Thompson') and a title like 'Talent Acquisition Lead'. 
Do NOT use placeholders like [Name] or [Recruiter]."""

        # Using Haiku model
        message = client.messages.create(
            model="claude-3-haiku-20240307",
            max_tokens=1024,
            messages=[{
                "role": "user",
                "content": prompt
            }]
        )
        
        rejection_text = message.content[0].text
        
        # Email sending
        email_sent = False
        if email:
            email_sent, _ = send_rejection_email(email, rejection_text, company, role)
        
        return jsonify({
            'success': True,
            'rejection_letter': rejection_text,
            'count': new_count, # This sends the updated number to the frontend
            'company': company,
            'role': role,
            'email_sent': email_sent
        })
        
    except Exception as e:
        print(f"CRITICAL ERROR: {str(e)}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@app.route('/health', methods=['GET'])
def health():
    return jsonify({'status': 'healthy'})

if __name__ == '__main__':
    app.run(debug=True, port=5000)
